name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      run: sudo apt-get install -y php php-cli php-mbstring php-xml php-zip php-gd php-intl php-calendar

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env file
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Update .env file
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Run Laravel tests
      run: php artisan test

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      run: sudo apt-get install -y php php-cli php-mbstring php-xml php-zip php-gd php-intl php-calendar

    - name: Copy .env file
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Update .env file
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader --no-dev

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Clear caches
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
